name: "CI/CD"
on: [push]
jobs:
  command:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        run: yarn
      - name: jest
        run: yarn test
